services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    container_name: minio_container
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: on-failure
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-storage:/data

volumes:
  pg-data:
  minio-storage: