scrape_configs:
  - job_name: '[Metrics] SocialNetworkAI API'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['application:8080','host.docker.internal:8080']
        labels:
          application: 'Application'